Algoritmo "Exercício 4 - Carro com custos"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : condição do número
// Autor(a)    : Jeniffer Silva
// Data atual  : 08/09/2022
Var
// Seção de Declarações das variáveis
valor:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

Escreval("Escreva um número: ")
Leia(valor)
se valor >=0 entao
Escreval("Positivo")
senao
Escreval("Negativo")
fimse

Fimalgoritmo
